apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        fleet: canary
    spec:
      containers:
      - name: nginx
        image: nginx:1.10.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
