apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-b
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        fleet: b
    spec:
      containers:
      - name: nginx
        image: nginx:1.10.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
